### PR TITLE
Added New-VolumeShadowCopy and Remove-VolumeShadowCopy Cmdlets

### PR DESCRIPTION
**Pull request by Invoke-IR**
I added the ability to create a new VSC and remove a VSC.  We got on a DC that didnt have any ShadowCopies, so we had to create them ourselves.... and then realized that we should probably be able to clean up after ourselves.

### CODE REVIEW

**Comment by secabstraction** [comment]
You should really add an option to remove a particular volume shadow copy instead of all of them, e.g. you get on a box that already has VSCs and you make a more current one and only want to delete the one you created. That's what I did in invoke-wmishadowcopy ;)

**Comment by Invoke-IR** [comment]
Oh Jesse! The capability is there via the InputObject or DevicePath parameters, but I suppose it could use another example to show this functionality.

**Comment by mattifestation** [comment]
This is great Jared. Thank for the PR. I can definitely pull these in but some things to consider first. Since New-VolumeShadowCopy requires elevated privileges, perhaps you should first confirm that the VSS service is running and if not, start it.

Also, I think you're over-engineering Remove-VolumeShadowCopy. I think it should simply take in the raw DeviceObject paths and delete them accordingly. You can achieve this in a one-liner essentially. Consider the following modification:

```powershell
filter Remove-VolumeShadowCopy
{
<#
.SYNOPSIS

    Deletes a volume shadow copy.

    PowerSploit Function: Remove-VolumeShadowCopy
    Author: Jared Atkinson (@jaredcatkinson)
    License: BSD 3-Clause
    Required Dependencies: None
    Optional Dependencies: None
    Version: 2.0.0

.DESCRIPTION

    Remove-VolumeShadowCopy deletes a volume shadow copy from the system.

.PARAMETER DevicePath

    Specifies the volume shadow copy 'DeviceObject' path. This path can be retrieved with the Get-VolumeShadowCopy PowerSploit function or with the Win32_ShadowCopy object.

.EXAMPLE

    Get-VolumeShadowCopy | Remove-VolumeShadowCopy

    Description
    -----------
    Removes all volume shadow copy

.EXAMPLE

    Get-WmiObject Win32_ShadowCopy | Remove-VolumeShadowCopy

    Description
    -----------
    Removes all volume shadow copy

.EXAMPLE

    Remove-VolumeShadowCopy -DevicePath '\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy4'

    Description
    -----------
    Removes the volume shadow copy at the 'DeviceObject' path \\?\GLOBALROOT\DeviceHarddiskVolumeShadowCopy4
#>
    Param(
        [Parameter(Mandatory = $True, ValueFromPipeline = $True)]
        [ValidatePattern('^\\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy[0-9]{1,3}$')]
        [String]
        $DevicePath
    )

    Get-WmiObject -Namespace root\cimv2 -Class Win32_ShadowCopy |
        Where-Object {$_.DeviceObject -eq $DevicePath} |
            ForEach-Object { $_.Delete() }
}
```

That's a bit cleaner, no? I generally strongly advise against parameters that accept [Object]s unless there's a very good reason.

**Comment by mattifestation** [comment]
Also, I would consider Get-VolumeShadowCopy to be an optional dependency since you're including it in the examples.

**Comment by Invoke-IR** [comment]
I like the idea of starting the VSS Service... I'll do some testing on that and resubmit.

For the Remove-VSC cmdlet, I'd like to keep the functionality of removing all vsc if no specific path is given, but I think using the DevicePath is better than the whole object for the same reasons you stated.

**Comment by mattifestation** [comment]
"I'd like to keep the functionality of removing all vsc if no specific path is given." That being the case, this is the perfect example of supporting the -Whatif parameter. :)

**Comment by Invoke-IR** [comment]
Good point.  I think by convention all "Remove" cmdlets should support "ShouldProcess".

**Comment by Invoke-IR** [comment]
I think it may be useful to add a -ComputerName option to Get-VolumeShadowCopy, New-VolumeShadowCopy, and Remove-VolumeShadowCopy. All three of these cmdlets should natively support remoting through WMI

**Comment by mattifestation** [comment]
That's fine but then you would also need to include the following relevant parameters:

-Authentication
-Credential
-Impersonation
-ThrottleLimit

I personally only ever intended for the VSS functions to be executed locally only because there was no logical remote equivalent for Mount-VolumeShadowCopy. That, and I didn't see the value in being able to view and remove shadow copies remotely. That said, it's not like it's much work to add those parameters and then pass them to the WMI cmdlets via splatting.

**Comment by Invoke-IR** [comment]
Agreed. I'm happy with how it is now.

**Comment by mattifestation** [comment]
Thank you, sir!

**Pull request merged**
